// ─────────────────────────────────────────────────────────────────────────────
// THE APEX ROUTER — `nikatru.com/<id>/*` serves the app; everything else is the
// static marketing/legal site, untouched.
//
//   browser → nikatru.com/subscriptiontracker/…
//                │
//                ├─ first path segment in app-routes.json?
//                │     no  → next()                    → sites/nikatru asset
//                │     yes → fetch(row.origin + rest)  → that app's own Pages project
//                │
//                └─ /apps/subscriptiontracker, /pricing, /privacy, /legal/**  served as before
//
// ── WHY THIS EXISTS [ADR 075] ────────────────────────────────────────────────
// Paddle approves a DOMAIN and says of a subdomain "you will need to have that
// subdomain approved separately"; its overlay enforces AT INIT, against the PAGE
// ORIGIN. So on `<id>.nikatru.com` in-app checkout could not open at all, and
// every new app cost a fresh submission. Razorpay wants a support ticket per
// sub-domain against a ceiling of one main site plus five. Neither conditions
// anything on a PATH. One apex approval, held once, covers app #51.
//
// ── WHY A PAGES FUNCTION AND NOT A ROUTER WORKER ─────────────────────────────
// Both can proxy. The question that decided it was ROLLBACK GRANULARITY, and it
// was settled by measurement on 2026-09-09 rather than by argument:
//
//   · Under this design each app keeps its OWN Direct Upload Pages project with
//     its OWN deployment history. Rolling one app back is
//     `POST /accounts/{a}/pages/projects/{app}/deployments/{id}/rollback`.
//     MEASURED on two throwaway projects: rolling app B back flipped
//     `/appb/version.json` from V2 to V1 while `/subscriptiontracker/version.json` and the
//     ROUTER'S OWN DEPLOYMENT ID were both unchanged. Blast radius: one app.
//   · A router Worker has ONE version history for the whole script
//     (`/workers/scripts/{name}/versions` is script-scoped; there is no
//     per-route version). Rolling it back rolls back the routing for EVERY app
//     at once. Restoring per-app granularity means one Worker plus one zone
//     route PER APP — a Cloudflare console step for app #2, which is exactly
//     the cost this design exists to avoid.
//   · And a Worker on `nikatru.com/*` would put the frozen legal archive behind
//     a Worker. Larger blast radius for a worse rollback story.
//
// A `_redirects` file was never a candidate: Cloudflare Pages supports 3xx and
// SAME-PROJECT 200 rewrites only. There is no proxy-to-another-origin form.
//
// ── THE FAILURE MODE IS `next()`, DELIBERATELY ───────────────────────────────
// 🔴 This file is the only thing between a visitor and `nikatru.com` — marketing,
// pricing, /checkout-return, and the dated consent archive under /legal/. A
// throw here takes all of it dark. So every branch that can fail falls THROUGH
// to the static site rather than erroring: a malformed table, a route row
// missing an origin, an upstream that will not answer. The app path breaks; the
// studio does not.
//
// Two layers of that, and they are different:
//   · BUILD TIME — `app-routes.json` is a static import, so bytes that are not
//     JSON fail the Functions bundle, the Pages build fails, and the PREVIOUS
//     deployment goes on serving. Nothing is published broken.
//   · RUN TIME  — JSON that parses but is the wrong SHAPE (an object, a row with
//     no origin) is caught below and routed to `next()`.
//
// ── WHY THE PROXY TARGET IS *.pages.dev AND NOT <id>.nikatru.com ─────────────
// 🔴 The retired subdomain gets a zone Redirect Rule 301ing it to this path. A
// rule on `<id>.nikatru.com/*` sits in the nikatru.com zone; `*.pages.dev` does
// not. Fetching the pages.dev origin therefore CANNOT be caught by that rule —
// the loop is impossible by construction rather than exempted by a header some
// future rule edit could stop matching. `row.origin` comes from
// `hosts.pagesOrigin` in app.yaml, which is declared because Cloudflare appended
// a suffix when the project name was taken (`subly-9cp.pages.dev`), so
// `<id>.pages.dev` is wrong for exactly the app this repository has.
//
// ── WHAT THIS FILE DOES NOT OWN ──────────────────────────────────────────────
// ⛔ `app-routes.json` is GENERATED by tooling/sites/generate-discovery.mjs from
// `catalog/apps.json`. Never hand-edit it; `site-drift-repair.yml` regenerates
// the discovery surface on every merge and opens a self-merging PR when the
// committed bytes drift, so a hand edit is undone by machinery.
// ⛔ Response headers for an app path. MEASURED 2026-09-09 on a throwaway Pages
// project: `_headers` is applied by the ASSET-serving stage, so it lands on
// `next()` responses and NOT on a response this function returns from a proxy
// fetch. The app's headers are therefore the app's own `apps/<id>/web/_headers`,
// which is what makes a per-app CSP possible at all — and what makes an app with
// NO declared CSP ship with none. See that file.
// ─────────────────────────────────────────────────────────────────────────────
import table from '../app-routes.json';

/** Paths the router must never claim, whatever the table says.
 *
 *  🔴 `/.well-known/` is ORIGIN-SCOPED BY SPECIFICATION. `assetlinks.json` and
 *  `apple-app-site-association` are fetched by Android and iOS from the ORIGIN,
 *  never from a path, so on one shared origin they are ONE file for the whole
 *  portfolio and they must be served by the apex itself. Proxying them to an app
 *  would hand one app the deep-link verification of every other app. */
const NEVER_PROXY = ['/.well-known/'];

/** The table, validated once at module scope. Anything that is not an array of
 *  `{path, origin}` rows collapses to an EMPTY table, which makes every request
 *  a `next()` — the site serves, the apps 404 into the marketing 404, and the
 *  drift is loud rather than fatal. */
const routes = (() => {
  try {
    if (!Array.isArray(table)) return [];
    return table.filter(
      (r) =>
        r &&
        typeof r.path === 'string' &&
        /^\/[a-z0-9][a-z0-9_-]*$/.test(r.path) &&
        typeof r.origin === 'string' &&
        r.origin.startsWith('https://'),
    );
  } catch {
    return [];
  }
})();

/** 🔴 THE SECURITY HEADER SET A PROXIED RESPONSE WOULD OTHERWISE HAVE NONE OF.
 *
 *  MEASURED 2026-09-09 on a throwaway Pages project, and independently asserted
 *  by `assert-web-cache-policy.mjs`'s Functions limb: `_headers` is applied by
 *  the ASSET-serving stage, so it lands on a `next()` response and NOT on one
 *  this function returns from a proxy fetch. Without this block the app path
 *  would answer with no header policy at all while every static page on the same
 *  origin carried the full set.
 *
 *  ⚠️ APPLIED ONLY WHERE THE APP DECLARED NOTHING. The app's own bytes come with
 *  the app's own `apps/<id>/web/_headers`, and that file — not this one — is
 *  where a per-app policy belongs: it is the whole reason this design proxies
 *  instead of merging every app into one Pages project, where a single `_headers`
 *  would have to hold the UNION and the weakest policy would apply everywhere.
 *  Overwriting here would take that back. Setting TWO `Content-Security-Policy`
 *  headers would be worse still: browsers enforce the INTERSECTION, so a correct
 *  app policy plus this fallback would block the app in a way neither policy
 *  describes.
 *
 *  The CSP below is therefore a FLOOR for an app that declares none — deliberately
 *  strict, so that an app arriving without a policy fails loudly in its own
 *  console rather than silently inheriting nothing. `apps/subscriptiontracker/web/_headers`
 *  declares the real one, verified live against the running app on 2026-09-09. */
const SECURITY_HEADERS = {
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'DENY',
  'referrer-policy': 'strict-origin-when-cross-origin',
  'strict-transport-security': 'max-age=63072000; includeSubDomains; preload',
  'content-security-policy':
    "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'self'",
};

export async function onRequest(context) {
  const { request, next } = context;
  try {
    const url = new URL(request.url);

    for (const prefix of NEVER_PROXY) {
      if (url.pathname === prefix.slice(0, -1) || url.pathname.startsWith(prefix)) return next();
    }

    const segment = `/${url.pathname.split('/')[1] ?? ''}`;
    const row = routes.find((r) => r.path === segment);
    if (!row) return next();

    // `/subscriptiontracker` → `/subscriptiontracker/`. The build is compiled with `--base-href /<id>/`, so
    // every asset URL in the document is relative to the TRAILING SLASH. Serving
    // the document at the bare path would resolve `main.dart.js` against `/`
    // and 404 every asset — silently, as a blank page. A 301 (not 302): the
    // slashed form is the permanent address, and [ADR 075]'s whole instruction
    // was that a move is a move.
    if (url.pathname === segment) {
      return Response.redirect(`${url.origin}${segment}/${url.search}`, 301);
    }

    const rest = url.pathname.slice(segment.length);
    const target = new URL(rest + url.search, row.origin);

    // `redirect: 'manual'` so an upstream 3xx is RELAYED rather than followed
    // here — following it would hide an upstream redirect loop inside a single
    // apex response, and the browser is the right place to see the hop.
    const upstream = await fetch(new Request(target, request), { redirect: 'manual' });
    const out = new Response(upstream.body, upstream);
    for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
      if (!out.headers.has(name)) out.headers.set(name, value);
    }
    return out;
  } catch {
    // Every failure is the static site, never a 500 on the apex.
    return next();
  }
}
