#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// render.mjs — apps/<id>/app.yaml is the source; the catalogue and the listing
// copy are RENDERINGS.
//
//     apps/<id>/app.yaml ──(this script)──▶ catalog/apps.json
//                                        ├▶ apps/<id>/store/<channel>/title.txt
//                                        ├▶ …/short-description.txt
//                                        ├▶ …/category.txt
//                                        ├▶ …/privacy-policy-url.txt
//                                        └▶ …/support-url.txt
//
// ── WHAT THIS FIXES, IN THE GUARD'S OWN WORDS ────────────────────────────────
// `assert-store-metadata.mjs` opens with "[pipeline D-5] Store listing metadata
// is GENERATED from the spec and lives in the repo", and its own header then
// records that every subject it had was `apps/subly/store/`, "which a human
// wrote by hand". The guard was real, running and green while pointing one
// artifact away from the behaviour the requirement names. This script is the
// generator that sentence has been describing.
//
// ── THE BYTES ARE THE CONTRACT, AND TWO POSITIVE CONTROLS READ THEM ──────────
// 🔴 `catalog/apps.json` IS COMPARED BYTE FOR BYTE by tests that run on the real
// tree (TRAPS ci-31): `generate-apps-data.test.mjs` regenerates the site feed
// from it and asserts byte equality with the committed feed, and the site lane
// deletes and regenerates that feed and runs `git diff --exit-code`. So this
// renderer reproduces the catalogue's HAND-WRITTEN house style exactly — two
// space indent, an array of scalars inline as `[a, b]` — and NOT
// `JSON.stringify(x, null, 2)`, which expands `"platforms": ["web"]` to three
// lines and turns a 410-byte file into a different one. The same encoder,
// character for character, is `_encodeCatalogue` in
// tooling/bricks/app/hooks/post_gen.dart and `serialise` in
// tooling/sites/generate-apps-data.mjs; all three exist because Dart writes the
// file at stamp time, Node renders it here, and Node reads it there.
//
// ⚠️ The obvious one-liner for the inline case — `JSON.stringify(v).replace(/,/g,
// ', ')` — is WRONG and its wrongness is invisible on today's data: it rewrites
// commas inside string values too, so `["a,b"]` becomes `["a, b"]`. Encoding each
// element and joining is comma-safe by construction.
//
// ── THE LISTING FILES CARRY NO "GENERATED" HEADER, AND CANNOT ────────────────
// `title.txt` IS the title a store shows. A `# DO NOT EDIT` line in it would be
// submitted to Google Play as part of the app's name. There is no comment syntax
// available in a file whose entire content is the value, so `--check` is the only
// thing standing between a hand edit and a store console — exactly the position
// `generate-apps-data.mjs` records for the site feed, which is JSON and has the
// same problem for the same reason.
//
// ── WHAT IT DELIBERATELY DOES NOT WRITE ──────────────────────────────────────
// ⛔ The four SWORN declarations — android-play/{data-safety,content-rating,
// ads-declaration}.json and ios-appstore/privacy-manifest.json. Those are
// statements about Subly's real code, each answer carrying its own citation, and
// [ADR 037]'s rule is that "a sworn declaration regenerated by a template is a
// statement nobody made". assert-sworn-store-files.mjs limb 7 is the tripwire and
// this script never opens those paths.
// ⛔ The EDITORIAL files — long-description.txt, keywords.txt, subtitle.txt,
// promotional-text.txt, search-terms.txt, snap-name.txt, license.txt. They are
// reviewed prose about what an app actually does; a renderer would replace them
// with filler true of no app in particular.
//
// Usage:  node tooling/app-yaml/render.mjs [root] [--check]
//         (default) writes every rendering whose bytes differ
//         --check   renders in memory and DIFFS; exit 1 NAMING each stale file
// Exit 0 = the tree matches the declarations. 1 = it does not (or a declaration
// is invalid). 2 = COVERAGE LOST — see the refusals in `plan`.
// ─────────────────────────────────────────────────────────────────────────────
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseYaml, YamlError } from './yaml.mjs';
import { validate } from './schema-validate.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));

export const APPS_DIR = 'apps';
export const CATALOGUE = 'catalog/apps.json';
export const REGISTER = 'tooling/channel-register.json';
export const APP_SCHEMA_PATH = join(HERE, 'schema', 'app.schema.json');

/** The listing files this script owns. Everything else under a channel tree is
 *  sworn or editorial — see the header. */
export const RENDERED_LISTING_FILES = ['title.txt', 'short-description.txt', 'category.txt', 'privacy-policy-url.txt', 'support-url.txt'];

/** The catalogue row's key order. Locked, because the row is the published record
 *  and the bytes are compared by two positive controls: a row whose keys arrive
 *  in whatever order the reader happened to produce is a file that reformats
 *  itself the first time a different tool writes it. */
const ROW_ORDER = ['slug', 'name', 'tagline', 'url', 'api', 'listings', 'platforms', 'markets', 'audience', 'status'];

/* ------------------------------------------------------------------ */
/* Serialisation — the catalogue's hand-written house style           */

export function serialise(value, indent = '') {
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    if (value.every((el) => el === null || typeof el !== 'object')) {
      return `[${value.map((el) => JSON.stringify(el)).join(', ')}]`;
    }
    return `[\n${value.map((el) => `${indent}  ${serialise(el, `${indent}  `)}`).join(',\n')}\n${indent}]`;
  }
  if (value && typeof value === 'object') {
    const keys = Object.keys(value);
    if (keys.length === 0) return '{}';
    const inner = keys.map((k) => `${indent}  ${JSON.stringify(k)}: ${serialise(value[k], `${indent}  `)}`).join(',\n');
    return `{\n${inner}\n${indent}}`;
  }
  return JSON.stringify(value);
}

/* ------------------------------------------------------------------ */
/* Plan                                                               */

const read = (root, rel) => (existsSync(join(root, rel)) ? readFileSync(join(root, rel), 'utf8') : null);
const isDir = (p) => existsSync(p) && statSync(p).isDirectory();

/**
 * Read every declaration and compute every rendering. Nothing is written here.
 *
 * Returns `{ declarations, files, problems, lost }`, where `files` is a Map of
 * repository-relative path -> exact bytes, `problems` is a list of authoring
 * errors (exit 1) and `lost` is a list of coverage failures (exit 2).
 *
 * 🔴 THE COVERAGE REFUSALS, AND WHY EACH IS 2 RATHER THAN 0. Every one of them
 * describes a run that compared NOTHING and would otherwise print ok:
 *   · no apps/ directory                 — the source set is empty
 *   · zero app.yaml files                — nothing declares, so nothing renders
 *   · the channel register is unreadable — the storefront key set and the store
 *                                          directories both come from it, so
 *                                          `listings` would silently lose keys
 *                                          and no listing file would be rendered
 *   · a declaration exists and yields
 *     zero listing files                 — the store trees moved out from under
 *                                          the renderer and the only thing left
 *                                          being checked is the catalogue
 */
export function plan(root) {
  const problems = [];
  const lost = [];
  const files = new Map();
  const declarations = [];

  const appsAbs = join(root, APPS_DIR);
  if (!isDir(appsAbs)) {
    lost.push(`${APPS_DIR}/ does not exist, so this run had no declaration to render from.`);
    return { declarations, files, problems, lost };
  }

  const registerRaw = read(root, REGISTER);
  if (registerRaw === null) {
    lost.push(`${REGISTER} is missing. It is the ONE declaration of which storefronts exist and where each channel's listing tree lives; without it the rendered \`listings\` block would silently lose keys and no listing file would be written at all.`);
    return { declarations, files, problems, lost };
  }
  let register;
  try {
    register = JSON.parse(registerRaw);
  } catch (e) {
    lost.push(`${REGISTER} is not valid JSON (${e.message}); the storefront key set cannot be derived.`);
    return { declarations, files, problems, lost };
  }
  const channels = Array.isArray(register.channels) ? register.channels : [];
  const storefronts = channels.filter((c) => c && typeof c.storefrontKey === 'string' && c.storefrontKey !== '');
  if (storefronts.length === 0) {
    lost.push(`${REGISTER} names no \`storefrontKey\`. An empty \`listings\` block advertises nothing and satisfies nothing.`);
    return { declarations, files, problems, lost };
  }
  const storeRows = channels.filter((c) => c && c.kind === 'store' && typeof c.storeMetadataDir === 'string' && c.storeMetadataDir.includes('{app}'));
  if (storeRows.length === 0) {
    lost.push(`${REGISTER} declares zero \`kind: "store"\` rows with a \`storeMetadataDir\`. Every listing file below is written into one of those directories, so the listing half of this renderer would cover nothing.`);
    return { declarations, files, problems, lost };
  }

  const schema = JSON.parse(readFileSync(APP_SCHEMA_PATH, 'utf8'));

  const ids = listDirs(appsAbs).filter((id) => existsSync(join(appsAbs, id, 'app.yaml'))).sort();
  if (ids.length === 0) {
    lost.push(`no ${APPS_DIR}/<id>/app.yaml exists. Zero declarations render zero bytes and every comparison below would pass over an empty set.`);
    return { declarations, files, problems, lost };
  }

  for (const id of ids) {
    const rel = `${APPS_DIR}/${id}/app.yaml`;
    let doc;
    try {
      doc = parseYaml(readFileSync(join(root, rel), 'utf8'));
    } catch (e) {
      problems.push(`${rel}: ${e instanceof YamlError ? e.message : String(e)}`);
      continue;
    }
    const bad = validate(doc, schema, rel);
    if (bad.length) {
      for (const b of bad) problems.push(b);
      continue;
    }
    if (doc.id !== id) {
      problems.push(`${rel}: declares id "${doc.id}" but lives in ${APPS_DIR}/${id}/. The directory name is the app id everywhere else in this tree.`);
      continue;
    }
    const declared = doc.listings ?? {};
    if (Object.hasOwn(declared, 'web')) {
      problems.push(`${rel}: \`listings.web\` is DERIVED from hosts.web and must not be written. Two spellings of one fact is what assert-catalog-contract.mjs fails a row for.`);
      continue;
    }
    const unknown = Object.keys(declared).filter((k) => !storefronts.some((c) => c.storefrontKey === k));
    if (unknown.length) {
      problems.push(`${rel}: \`listings\` names ${unknown.map((u) => `"${u}"`).join(', ')}, which ${REGISTER} does not declare as a storefrontKey.`);
      continue;
    }
    declarations.push({ id, rel, doc });
  }
  if (declarations.length === 0) {
    if (problems.length === 0) lost.push('every declaration was skipped without a recorded problem — this run graded nothing.');
    return { declarations, files, problems, lost };
  }

  // ── the catalogue ─────────────────────────────────────────────────────────
  const rows = declarations.map(({ doc }) => {
    const url = `https://${doc.hosts.web}`;
    const declared = doc.listings ?? {};
    const listings = {};
    for (const c of storefronts) {
      listings[c.storefrontKey] = c.kind === 'web' ? url : (declared[c.storefrontKey] ?? null);
    }
    const row = {
      slug: doc.id,
      name: doc.name,
      tagline: doc.tagline,
      url,
      api: doc.hosts.api ? `https://${doc.hosts.api}` : '',
      listings,
      platforms: doc.platforms,
      markets: doc.markets,
      audience: doc.audience,
      status: doc.status,
    };
    const ordered = {};
    for (const k of ROW_ORDER) if (row[k] !== undefined) ordered[k] = row[k];
    return ordered;
  });
  files.set(CATALOGUE, `${serialise(rows)}\n`);

  // ── the listing copy ──────────────────────────────────────────────────────
  // Written ONLY into a channel directory that already exists. Creating one is
  // the stamp's job and, for the four channels with no publisher account, an
  // owner-gated decision — assert-store-metadata.mjs PRINTS a missing tree on a
  // deferred row and FAILS an incomplete one, and a renderer that conjured trees
  // would turn that owner-gated print into a commitment nobody made.
  let listingFiles = 0;
  for (const { id, doc } of declarations) {
    for (const c of storeRows) {
      const dir = c.storeMetadataDir.replace('{app}', id);
      if (!isDir(join(root, dir))) continue;
      const values = {
        'title.txt': doc.name,
        'short-description.txt': doc.tagline,
        'category.txt': doc.category,
        'privacy-policy-url.txt': doc.legal.privacyPolicyUrl,
        'support-url.txt': doc.legal.supportUrl,
      };
      for (const f of RENDERED_LISTING_FILES) {
        files.set(`${dir}/${f}`, `${values[f]}\n`);
        listingFiles += 1;
      }
    }
  }
  if (listingFiles === 0) {
    lost.push(
      `${declarations.length} declaration(s) rendered ZERO listing files: not one of the ${storeRows.length} store directories ` +
        `${REGISTER} declares exists under any of them. The listing half of this renderer covered nothing, and the catalogue ` +
        'alone is not what [10]D-5 is about.',
    );
  }
  return { declarations, files, problems, lost };
}

function listDirs(abs) {
  return readdirSync(abs, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name);
}

/* ------------------------------------------------------------------ */
/* Main                                                               */

export function render(root, { check = false } = {}) {
  const { files, problems, lost } = plan(root);
  if (lost.length) return { code: 2, lost, problems, stale: [], wrote: [] };
  if (problems.length) return { code: 1, lost, problems, stale: [], wrote: [] };
  const stale = [];
  const wrote = [];
  for (const [rel, contents] of files) {
    const abs = join(root, rel);
    const current = existsSync(abs) ? readFileSync(abs, 'utf8') : null;
    if (current === contents) continue;
    stale.push(rel);
    if (!check) {
      mkdirSync(dirname(abs), { recursive: true });
      writeFileSync(abs, contents);
      wrote.push(rel);
    }
  }
  return { code: check && stale.length ? 1 : 0, lost, problems, stale, wrote, total: files.size };
}

const invokedDirectly = process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));
if (invokedDirectly) {
  const args = process.argv.slice(2);
  const check = args.includes('--check');
  const positional = args.filter((a) => !a.startsWith('--'));
  const root = resolve(positional[0] ?? join(HERE, '..', '..'));
  const r = render(root, { check });
  if (r.code === 2) {
    console.error('');
    for (const l of r.lost) console.error(`FAIL COVERAGE LOST — ${l}`);
    console.error('\nrender: COVERAGE LOST');
    process.exit(2);
  }
  if (r.problems.length) {
    for (const p of r.problems) console.error(`✗ ${p}`);
    console.error(`\nrender: ${r.problems.length} problem(s) in the declarations — nothing was written.`);
    process.exit(1);
  }
  if (check) {
    if (r.stale.length) {
      console.error('✗ these renderings no longer match their declaration:');
      for (const s of r.stale) console.error(`    ${s}`);
      console.error('\n  Change the declaration, not the rendering, then:  node tooling/app-yaml/render.mjs');
      process.exit(1);
    }
    console.log(`ok   render --check — ${r.total} rendering(s) match apps/*/app.yaml`);
    process.exit(0);
  }
  if (r.wrote.length) for (const w of r.wrote) console.log(`wrote ${w}`);
  console.log(`ok   render — ${r.total} rendering(s) from apps/*/app.yaml, ${r.wrote.length} rewritten`);
  process.exit(0);
}
